language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t cameljohn/docker-practice -f Dockerfile.dev .

script:
  - docker run -e CI=true cameljohn/docker-practice npm run test